apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuid-server-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: kuid-server
  namespace: kuid-system