apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuid-server-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuid-server-clusterrole
subjects:
- kind: ServiceAccount
  name: kuid-server
  namespace: kuid-system