apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuid-server-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: kuid-server
  namespace: kuid-system
