apiVersion: v1
kind: Service
metadata:
  name: kuid-server-metrics
  namespace: kuid-system
  labels:
    app.kubernetes.io/name: kuid-server
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: kuid-server
