apiVersion: v1
kind: Service
metadata:
  name: kuid-server
  namespace: kuid-system
  labels:
    app.kubernetes.io/name: kuid-server
spec:
  ports:
  - port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app.kubernetes.io/name: kuid-server
